#!/usr/bin/env python

import random
import sys

def parse_byte_size(s):
    result = -1
    number = float(s[0:len(s)-1])
    suffix = s[len(s)-1:len(s)]
    if suffix == "K":
        result = int(1024 * number)
    if suffix == "M":
        result = int(1024 * 1024 * number)
    if suffix == "G":
        result = int(1024 * 1024 * 1024 * number)
    return result

def usage():
    print "\n  Usage:"
    print "    %s output [size]" % sys.argv[0]
    print "\n  Examples:"
    print "    %s dataset.csv" % sys.argv[0]
    print "    %s dataset.csv 128M" % sys.argv[0]
    print "    %s dataset.csv 1.5G" % sys.argv[0]
    print
    sys.exit(1)

if len(sys.argv) < 2:
  usage()

filename  = sys.argv[1]

if len(sys.argv) == 3:
    file_size = parse_byte_size(sys.argv[2])
else:
    file_size = 128 * 1024 * 1024 # 128 MB

if file_size < 0:
    usage()

symbol    = "AAPL"
last      = 100.0
timestamp = 34200000
length    = 0

outfile = open(filename, 'w')

line = "Symbol,Timestamp,Last\n"
length += len(line)
outfile.write(line)

while length < file_size:
    last      += random.uniform(-1.0, 1.0)
    timestamp += random.randint(500, 2000)

    line = "%s,%d,%.2f\n" % (symbol, timestamp, last)
    length += len(line)
    outfile.write(line)
